### ISSUE TITLE
RECESS should be analyzing CSS files

### ISSUE THREAD

**Issue by seandrickson** [AtomLinter/linter-recess#1]
Check out the [RECESS repo examples](https://github.com/twitter/recess#examples) for more information. The idea is that it will compile your Less for you and then report any errors with your code afterwards. It's a linter and compiler in one (like tidy for HTML).

**Comment by Arcanemagus** [comment]
This is currently on [the list](https://github.com/AtomLinter/Meta/issues/9) of linters that require a re-write, if you would like to take it up that would be great!
